### ISSUE TITLE
Plugin publishes Coming Soon! Default Article, but not the intended post

### ISSUE THREAD

**Issue by hungry-bogart** [Southpaw1496/obsidian-send-to-ghost#1]
I'd be happy to provide more info, but the gist is that when you enable the plugin according to the directions in the README for this repo, it seems that the intended post doesn't generate.

I'm going to clear up that I generated the custom integration, added my url and API key, applied the appropriate front matter from the template, but have not seen an actual post on my ghost instance.

Not sure why. If you want screenshots, term output, let me know.

Also, this is still maintained correct?

**Comment by Southpaw1496** [comment]
Yes, it is still maintained. I haven't made any updates in a while because the plugin is designed with fairly old Obsidian versions in mind, and bringing it in line with more modern versions will require a full rewrite. I don't have time to focus on that yet, but it also means that I don't want to add new features to the outdated design, so my goal for the moment is to keep it working.

There are a few things I can immediately think of based on what you've said: 
- You may have copied the **Content** API key instead of the **Admin** API Key. The content API key is read-only, the admin key is what you need.
- You may not have copied the admin key correctly. It should be 24 alphanumeric characters, followed by a colon (`:`), followed by 64 alphanumeric characters. Some browsers don't copy the characters after the colon if you're not careful.
- You may have put in your API URL without `https://` at the front.

If none of those things work, the exact error may appear in the console. You can access the console by pressing `Ctrl-Alt-i` on Windows, or `Cmd-Opt-i` on macOS, or clicking "Toggle Developer Tools" in the View menu. Be careful to redact anything sensitive that's there before posting it here.

**Comment by hungry-bogart** [comment]
Hey, Southpaw

I just checked the integration again and I was excited to see that it worked. I will share my bonehead mistake just in case it helps someone.

I was building Ghost with Docker-Compose and I think my blog was restarting every time as if it was a brand new installation. So the integration settings (Admin API/URL) were no longer set or valid.

I added my volumes and restarted Ghost and it worked the first try. Thanks for the help and the awesome plugin!
